### ISSUE TITLE
Melody Pottery Sherd Pattern doesn't work properly on 1.20.1

### ISSUE THREAD

**Issue by KekeCreations** [Codeywrm/dwdsb-old#1]
Hi I'm on version dwdsb-1.5.1 on 1.20.1 and whenever I use the melody pottery sherds, the normal side texture is displayed instead of the pattern.

**Comment by KekeCreations** [comment]
Nvm on further research its because I didn't have the sherd api installed. Ideally the sherd api should be marked as a dependency in the fabric.mod.json to stop the game from loading without it

**Comment by Codeywrm** [comment]
(As you know) working on an update for 1.20.1 that removes the need for the SherdAPI. Thanks for the heads up!
